import {type WebSite, WebSiteImpl} from "../jopiWebSite.js";
import {getVirtualUrlMap, type VirtualUrlEntry} from "./extraContent.js";

/**
 * Server the /_bundle and /_bundle_s directories.
 * /_bundle/**: files generated by esbuild.
 * /_bundle_s/**: virtual url pointing to the bundle resoures.
 */
export function installBundleServer(webSite: WebSite) {
    const virtualRoutes = getVirtualUrlMap();

    webSite.onGET("/_bundle/**", async (req) => {
        req.urlInfos.pathname = req.urlInfos.pathname.substring("/_bundle".length);
        return req.serverFromDir(gDirToServe!);
    });

    // Serve /_bundle_s/** resources.
    //
    // It's url pointing to the transformed url generated by the bundler.
    // This url comes from jopi-loader when processing the initial import.
    // The difficult here is that the import is done before the bundling step,
    // and it's why we don't know the final url before time.
    //
    virtualRoutes.forEach(e => addVirtualUrl(webSite, e));
}

function addVirtualUrl(webSite: WebSite, entry: VirtualUrlEntry) {
    if (!entry.bundleFile) return;

    const toServe = entry.bundleFile;
    webSite.onGET(entry.route, async req => {
        return req.returnFile(toServe);
    });
}

function getBundleUrl(webSite: WebSite): string {
    return (webSite as WebSiteImpl).welcomeUrl + "/_bundle";
}

export function getBundleEntryPointUrl_JS(webSite: WebSite): string {
    return getBundleUrl(webSite) + '/' + gJsEntryPointFileName;
}

export function getBundleEntryPointUrl_CSS(webSite: WebSite): string {
    return getBundleUrl(webSite) + '/' + gCssEntryPointFileName;
}

export function configureServer(dirPath: string, jsEntryPointFileName: string, cssEntryPointFileName?: string) {
    gDirToServe = dirPath;
    gJsEntryPointFileName = jsEntryPointFileName;
    gCssEntryPointFileName = cssEntryPointFileName;
}

let gDirToServe: string|undefined;
let gJsEntryPointFileName: string|undefined;
let gCssEntryPointFileName: string|undefined;